[tool.poetry]
name = "py_jwt_cpp"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.5"

[tool.poetry.group.dev.dependencies]
pybind11 = "^2.13.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
